version: "3.8"
services:
  api_proxy:
    container_name: api_proxy
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "5010:5000"
    environment:
      - NODE_ENV=production
